// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.authentication;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_authentication_AuthenticationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_authentication_AuthenticationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_authentication_AuthenticationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_authentication_AuthenticationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_authentication_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_authentication_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_authentication_CreateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_authentication_CreateUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\022com.authentication\";\n\025Au" +
      "thenticationRequest\022\020\n\010username\030\001 \001(\t\022\020\n" +
      "\010password\030\002 \001(\t\"*\n\026AuthenticationRespons" +
      "e\022\020\n\010jwtToken\030\001 \001(\t\"7\n\021CreateUserRequest" +
      "\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"&\n\022" +
      "CreateUserResponse\022\020\n\010jwtToken\030\001 \001(\t2\204\001\n" +
      "\025AuthenticationService\022k\n\020authenticateUs" +
      "er\022).com.authentication.AuthenticationRe" +
      "quest\032*.com.authentication.Authenticatio" +
      "nResponse\"\0002r\n\021CreateUserService\022]\n\ncrea" +
      "teUser\022%.com.authentication.CreateUserRe" +
      "quest\032&.com.authentication.CreateUserRes" +
      "ponse\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_authentication_AuthenticationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_authentication_AuthenticationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_authentication_AuthenticationRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_com_authentication_AuthenticationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_authentication_AuthenticationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_authentication_AuthenticationResponse_descriptor,
        new java.lang.String[] { "JwtToken", });
    internal_static_com_authentication_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_authentication_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_authentication_CreateUserRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_com_authentication_CreateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_authentication_CreateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_authentication_CreateUserResponse_descriptor,
        new java.lang.String[] { "JwtToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
